import os
from google import genai


def get_gemini_client():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        return None
    return genai.Client(api_key=api_key)


def calculate_risk(aqi, water, waste, green):
    if aqi <= 50:
        aqi_score = 0
    elif aqi <= 100:
        aqi_score = 1
    elif aqi <= 150:
        aqi_score = 2
    elif aqi <= 200:
        aqi_score = 3
    elif aqi <= 300:
        aqi_score = 4
    else:
        aqi_score = 5

    score = aqi_score + water * 0.5 + waste * 0.5 + (10 - green) * 0.5

    if score < 6:
        level = "🟢 LOW"
    elif score < 11:
        level = "🟡 MODERATE"
    elif score < 16:
        level = "🟠 HIGH"
    else:
        level = "🔴 VERY HIGH"

    return level, round(score, 2)


def fallback_answer(city, aqi, temperature, water, waste, green):
    risk, score = calculate_risk(aqi, water, waste, green)

    if aqi <= 50:
        air = "The reported AQI is in the good range."
    elif aqi <= 100:
        air = "The reported AQI is in the moderate range."
    elif aqi <= 150:
        air = "The reported AQI may affect sensitive people."
    elif aqi <= 200:
        air = "The reported AQI indicates unhealthy air quality."
    elif aqi <= 300:
        air = "The reported AQI indicates very unhealthy air."
    else:
        air = "The reported AQI indicates hazardous-level air pollution."

    water_status = (
        "relatively low" if water <= 3 else
        "moderate" if water <= 6 else
        "high and requires attention"
    )
    waste_status = (
        "relatively low" if waste <= 3 else
        "moderate" if waste <= 6 else
        "high and requires attention"
    )
    green_status = (
        "relatively good" if green >= 7 else
        "moderate" if green >= 4 else
        "poor and additional vegetation may be beneficial"
    )

    return f"""# 🇵🇰 PakEco AI Environmental Report

## 🏙️ City
**{city}**

## ⚠️ Environmental Risk
# {risk}

**Risk Score: {score}/20**

---

## 🌍 Overall Environmental Status
The available user-entered indicators suggest an environmental risk level of **{risk}** for {city}.

## 🌫️ Air Quality
**AQI: {aqi}**

{air}

## 💧 Water Pollution
**Level: {water}/10**

The reported water pollution level is **{water_status}**.

## 🗑️ Waste Management
**Level: {waste}/10**

The reported waste pollution level is **{waste_status}**.

## 🌳 Ecosystem Condition
**Green Area Condition: {green}/10**

The reported green-area condition is **{green_status}**.

Temperature entered: **{temperature} °C**

## ⚠️ Main Environmental Concerns
- Air pollution based on the reported AQI
- Water pollution
- Waste management
- Green-area condition
- Potential effects on ecosystems and biodiversity

## 💡 Recommended Actions
- Improve waste collection and disposal.
- Avoid open burning of waste.
- Increase tree planting and green spaces.
- Protect local water resources.
- Improve public awareness about pollution.
- Use reliable monitoring data for official decisions.

## 🇵🇰 Citizen Advice
- Avoid burning household waste.
- Dispose of waste properly.
- Reduce unnecessary vehicle emissions.
- Protect trees and green areas.
- Avoid dumping waste into rivers, streams, and drains.

---

### ℹ️ Gemini Status
⚠️ Gemini was unavailable or rate-limited, so this report was generated by PakEco's local fallback system.

### ⚠️ Disclaimer
PakEco AI is an environmental screening prototype. User-entered values are not official government measurements.
"""


def generate_gemini_report(city, aqi, temperature, water, waste, green, risk, score):
    client = get_gemini_client()
    if client is None:
        return None

    prompt = f"""
You are PakEco AI, an environmental screening assistant for Pakistani cities.

City: {city}
AQI: {aqi}
Temperature: {temperature} °C
Water pollution: {water}/10
Waste pollution: {waste}/10
Green area condition: {green}/10
Calculated risk: {risk}
Risk score: {score}/20

Write a concise report using these exact sections:
## 🌍 Overall Environmental Status
## 🌫️ Air Quality
## 💧 Water Pollution
## 🗑️ Waste Management
## 🌳 Ecosystem Condition
## ⚠️ Main Environmental Concerns
## 💡 Recommended Actions
## 🇵🇰 Citizen Advice

Use simple English. Do not invent measurements. Clearly state that the values are user-entered and this is an AI screening prototype, not an official government system.
"""

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text if response and response.text else None


def analyze_environment(city, aqi, temperature, water, waste, green):
    try:
        if not city:
            return "❌ Please select a Pakistani city."

        aqi = float(aqi)
        temperature = float(temperature)
        water = float(water)
        waste = float(waste)
        green = float(green)

        if not 0 <= aqi <= 500:
            return "❌ AQI must be between 0 and 500."
        if not -20 <= temperature <= 60:
            return "❌ Temperature must be between -20°C and 60°C."
        if not 0 <= water <= 10:
            return "❌ Water pollution must be between 0 and 10."
        if not 0 <= waste <= 10:
            return "❌ Waste pollution must be between 0 and 10."
        if not 0 <= green <= 10:
            return "❌ Green area condition must be between 0 and 10."

        risk, score = calculate_risk(aqi, water, waste, green)

        try:
            gemini_report = generate_gemini_report(
                city, aqi, temperature, water, waste, green, risk, score
            )
            if gemini_report:
                return f"""# 🇵🇰 PakEco AI Environmental Report

## 🏙️ City
**{city}**

## ⚠️ Environmental Risk
# {risk}

**Risk Score: {score}/20**

---

{gemini_report}

---

## 📊 Input Data
| Indicator | Value |
|---|---:|
| 🌫️ AQI | {aqi} |
| 🌡️ Temperature | {temperature} °C |
| 💧 Water Pollution | {water}/10 |
| 🗑️ Waste Pollution | {waste}/10 |
| 🌳 Green Area Condition | {green}/10 |

### ⚠️ Disclaimer
PakEco AI is an environmental screening prototype. User-entered values are not official government measurements.
"""
        except Exception:
            pass

        return fallback_answer(city, aqi, temperature, water, waste, green)

    except Exception as error:
        return f"# ❌ PakEco Error\n\n`{error}`"
